---
title: "nbastatR Study"
output:
  html_document:
    highlight: tango
    self_contained: yes
    theme: flatly
    toc: yes
    toc_float: yes
  pdf_document: default
---

```{r setup, include=FALSE, warning= FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
```


```{r, echo=FALSE}
library(tidyverse)
library(nbastatR)
library(here)
library(rvest)
library(furrr)
library(magrittr)

source(here::here("R Tests", "functions_testing.R"))
source(here::here("R", "bref.R"))
# Functions
```

# Basketball Reference Functions

## Basketball Reference Player Season Tables

### Main Function
```{r, eval=FALSE}
# Overall Function
bref_players_stats <-
  function(seasons = NULL,
             tables = c("advanced", "totals"),
             include_all_nba = F,
             only_totals = TRUE,
             nest_data = FALSE,
             assign_to_environment = TRUE,
             widen_data = TRUE,
             join_data = TRUE,
             return_message = TRUE) {
    if (length(seasons) == 0) {
      stop("Enter season(s)")
    }
    # Take Tables Argument and Make into lowercase
    tables <-
      tables %>%
      str_replace_all("\\ ", "_") %>%
      str_to_lower()

    .get_data_bref_player_seasons_safe <-
      purrr::possibly(.get_data_bref_player_seasons, tibble())

    all_data <-
      tables %>%
      map_df(function(x) {
        .get_data_bref_player_seasons_safe(
          table = x,
          seasons = seasons,
          only_totals = only_totals,
          return_message = return_message
        )
      })

    all_data <-
      assign_bref_data(
        data = all_data,
        type = "Players",
        widen_data = widen_data,
        include_all_nba = include_all_nba,
        join_data = join_data,
        nest_data = nest_data,
        assign_to_environment = assign_to_environment
      )

    all_data <-
      all_data %>%
      mutate(yearSeason = slugSeason %>% substr(1, 4) %>% as.numeric() + 1)

    all_data
  }
```


Run Function to check output
```{r}
bref_player_stats_table <-
  bref_players_stats(
    seasons = 2018:2019,
    tables = c("advanced", "per_game"),
    include_all_nba = F,
    only_totals = TRUE,
    nest_data = FALSE,
    assign_to_environment = TRUE,
    widen_data = TRUE,
    join_data = TRUE,
    return_message = TRUE
  )

bref_player_stats_table %>% head(5)
```

### Component Breakdown of Main Function

-- User Custom Functions:
  - .get_data_bref_player_seasons
  
```{r}
# Arguments:
seasons <- 2018:2019
tables <- c("advanced", "per_game")
include_all_nba <- F
only_totals <- TRUE
nest_data <- FALSE
assign_to_environment <- TRUE
widen_data <- TRUE
join_data <- TRUE
return_message <- TRUE


# Take Tables Argument and Make into lowercase
tables <-
  tables %>%
  str_replace_all("\\ ", "_") %>%
  str_to_lower()
tables

.get_data_bref_player_seasons_safe <-
  purrr::possibly(.get_data_bref_player_seasons, tibble())

all_data <-
  tables %>%
  map_df(function(x) {
    .get_data_bref_player_seasons_safe(
      table = x,
      seasons = seasons,
      only_totals = only_totals,
      return_message = return_message
    )
  })
head(all_data, 5)

# Look inside dataTable column
preview <- all_data$dataTable[[1]]

head(preview, 5)

all_data <-
  assign_bref_data(
    data = all_data,
    type = "Players",
    widen_data = widen_data,
    include_all_nba = include_all_nba,
    join_data = join_data,
    nest_data = nest_data,
    assign_to_environment = assign_to_environment
  )
head(all_data, 5)

all_data <-
  all_data %>%
  mutate(yearSeason = slugSeason %>% substr(1, 4) %>% as.numeric() + 1)

head(all_data, 5)
```
### Internal Functions
#### .get_data_bref_player_seasons
##### Full Function
```{r, eval=FALSE}
.get_data_bref_player_seasons <-
  function(seasons = 2019,
             table = "advanced",
             only_totals = TRUE,
             return_message = TRUE) {
    current_season <- .get_current_season()
    urls <-
      .generate_years_urls(table = table, seasons = seasons)
    .parse_player_season_safe <-
      purrr::possibly(.parse_player_season, tibble())

    all_data <-
      urls %>%
      map_df(function(x) {
        .parse_player_season_safe(url = x, return_message = return_message)
      })

    all_data <-
      all_data %>%
      dplyr::select(-dplyr::matches("urlData")) %>%
      tidyr::unite(slugPlayerSeason, slugPlayerBREF, yearSeason, remove = F)


    all_data <-
      all_data %>%
      mutate(isSeasonCurrent = slugSeason == current_season) %>%
      select(typeData, slugSeason, isSeasonCurrent, everything())

    all_data <-
      all_data %>%
      mutate(yearSeason = slugSeason %>% substr(1, 4) %>% as.numeric() + 1)


    all_data <-
      all_data %>%
      arrange(yearSeason)

    df_players_teams <-
      all_data %>%
      filter(slugTeamBREF != "TOT") %>%
      group_by(slugPlayerBREF, slugSeason) %>%
      dplyr::summarise(
        slugTeamsBREF = str_c(slugTeamBREF, collapse = " | "),
        countTeamsPlayerSeason = length(slugTeamsBREF)
      ) %>%
      ungroup()

    all_data <-
      all_data %>%
      left_join(df_players_teams, by = c("slugSeason", "slugPlayerBREF"))

    if (only_totals) {
      all_data <-
        all_data %>%
        group_by(yearSeason, slugPlayerBREF) %>%
        filter(countGames == max(countGames)) %>%
        ungroup()
    }
    gc()

    all_data <-
      all_data %>%
      nest(-c(typeData, slugSeason, yearSeason), .key = dataTable)
    all_data
  }
```
##### Function Breakdown
```{r}
# Arguments
seasons <- 2018:2019
table <- "per_game"
only_totals <- TRUE
return_message <- TRUE

current_season <- .get_current_season()
current_season

urls <-
  .generate_years_urls(table = table, seasons = seasons)
urls

.parse_player_season_safe <-
  purrr::possibly(.parse_player_season, tibble())

all_data <-
  urls %>%
  map_df(function(x) {
    .parse_player_season_safe(url = x, return_message = return_message)
  })
head(all_data, 5)

all_data <-
  all_data %>%
  dplyr::select(-dplyr::matches("urlData")) %>%
  tidyr::unite(slugPlayerSeason, slugPlayerBREF, yearSeason, remove = F)
head(all_data, 5)

all_data <-
  all_data %>%
  mutate(isSeasonCurrent = slugSeason == current_season) %>%
  select(typeData, slugSeason, isSeasonCurrent, everything())
head(all_data, 5)

all_data <-
  all_data %>%
  mutate(yearSeason = slugSeason %>% substr(1, 4) %>% as.numeric() + 1)
head(all_data, 5)

all_data <-
  all_data %>%
  arrange(yearSeason)
head(all_data, 5)

# Create DF that counts number of teams per season for a player and changes column
df_players_teams <-
  all_data %>%
  filter(slugTeamBREF != "TOT") %>%
  group_by(slugPlayerBREF, slugSeason) %>%
  dplyr::summarise(
    slugTeamsBREF = str_c(slugTeamBREF, collapse = " | "),
    countTeamsPlayerSeason = length(slugTeamsBREF)
  ) %>%
  ungroup()

  all_data %>%
  filter(slugTeamBREF != "TOT") %>%
  group_by(slugPlayerBREF, slugSeason) %>%
  dplyr::summarise(
    count_teams = n(),
    slugTeamsBREF = str_c(slugTeamBREF, collapse = " | "),
    countTeamsPlayerSeason = length(slugTeamsBREF)
  ) %>%
  ungroup() %>% 
    arrange(desc(count_teams))
  


all_data <-
  all_data %>%
  left_join(df_players_teams, by = c("slugSeason", "slugPlayerBREF"))
head(all_data, 5)

if (only_totals) {
  all_data <-
    all_data %>%
    group_by(yearSeason, slugPlayerBREF) %>%
    filter(countGames == max(countGames)) %>%
    ungroup()
}
glimpse(all_data)


all_data <-
  all_data %>%
  nest(-c(typeData, slugSeason, yearSeason), .key = dataTable)
head(all_data)


all_data

glimpse(all_data[[1,4]])
```

#### .parse_player_season
##### Full Function
```{r, eval=FALSE}
.parse_player_season <-
  memoise::memoise(
    function(url = "http://www.basketball-reference.com/leagues/NBA_1997_per_game.html",
           return_message = TRUE) {
    ## case_when

    page <-
      url %>%
      read_html()
    # Creates df that has columns: scheme (http), hostname(www.basketball-reference.com), and path(leagues/NBA_1997_per_game.htm)
    url_df <- url %>% httr::parse_url() %>% flatten_df()
    # Returns "1997_per_game"
    url_path <-
      url_df$path %>% str_replace_all(".html|leagues/NBA_", '')

    year_season_end <-
      url_path %>% str_split('\\_') %>% flatten_chr() %>% .[[1]] %>% as.character() %>% readr::parse_number()

    name_slug <-
      url_path %>%
      map_chr(function(x) {
        parts <-
          x %>% str_split('\\_') %>% flatten_chr()

        parts[2:length(parts)] %>% str_to_title() %>% str_c(collapse = '')
      })

    id_season <-
      list(year_season_end - 1, '-', year_season_end %>% str_sub(3, 4)) %>%
      purrr::reduce(paste0)
    # Character Vector of Player Names
    players <-
      page %>%
      html_nodes('th+ .left a') %>%
      html_text()
    # Gets Player ID's Ex. "a/abdulma02.html"
    player_id <-
      page %>%
      html_nodes('th+ .left a') %>%
      html_attr('href') %>%
      # "/players/a/abdulma02.html"
      str_replace_all('/players/', '')

    player_ids <-
      player_id %>%
      map_chr(function(x) {
        x %>%
          # Get Player ID's and Remove .html. Ex. "a/abdulma02"
          str_replace_all('.html', '') %>%
          str_split('/') %>%
          flatten_chr() %>%
          .[[2]]
      })

    df_players <-
      tibble(slugPlayerBREF = player_ids, namePlayer = players) %>%
      distinct() %>%
      mutate(numberPlayer = 1:n()) %>%
      select(numberPlayer, everything())

    df <-
      page %>%
      html_table() %>%
      .[[1]] %>%
      data.frame(stringsAsFactors = FALSE) %>%
      tbl_df() %>%
      dplyr::select(-dplyr::matches("Var"))

    df <-
      df %>%
      mutate_at(df %>% dplyr::select(-one_of(c(
        "Tm", "Player", "Pos"
      ))) %>% names(),
      funs(. %>% as.numeric())) %>%
      filter(!Rk %>% is.na()) %>%
      suppressWarnings()

    # df_players_unique <-
    #   df %>% group_by(Rk) %>% slice(1) %>%
    #   select(numberPlayer = Rk, namePlayer = Player) %>%
    #   ungroup()
    #
    # df <-
    #   df %>%
    #   dplyr::select(-dplyr::matches("Rk"))

    df_names <-
      get_bref_name_df()

    bref_names <-
      names(df)

    actual_names <-
      seq_along(bref_names) %>%
      map_chr(function(x) {
        actual <-
          df_names %>%
          filter(nameBREF == bref_names[x]) %>%
          .$nameActual

        if (actual == 'MinutesPlayed') {
          if (!name_slug == 'pergame') {
            actual <-
              str_c('total', actual)
          } else {
            actual <-
              str_c('pergame', actual)
          }
          return(actual)
        }

        if (actual %>% substr(1, 1) %in% LETTERS) {
          actual <-
            str_c(name_slug, actual)
        }
        return(actual)
      })


    df <-
      df %>%
      purrr::set_names(actual_names) %>%
      mutate(
        isHOFPlayer = namePlayer %>% str_detect('\\*'),
        namePlayer = namePlayer %>% str_replace_all('\\*', '')
      )

    df <-
      df %>%
      left_join(df_players) %>%
      distinct() %>%
      suppressMessages() %>%
      mutate(slugSeason = id_season,
             yearSeason = year_season_end,
             urlData = url) %>%
      dplyr::select(slugSeason, yearSeason,
                    slugPlayerBREF, everything())

    df <-
      df %>%
      mutate_at(df %>% dplyr::select(dplyr::matches("pct")) %>% names(),
                funs(ifelse(. >= 1, . / 100, .))) %>%
      mutate(typeData = name_slug) %>%
      dplyr::select(typeData, everything())

    if (return_message) {
      list("parsed ", url) %>%
        purrr::reduce(paste0) %>%
        cat(fill = T)
    }
    df <- df %>%
      select(-one_of("numberPlayer"))

    df <- df %>%
      mutate_if(is.numeric, list(function(x){
        ifelse(is.na(x), 0, x)
      }))
    gc()
    df
  }
    )
```
##### Function Breakdown
```{r}
url <-  "http://www.basketball-reference.com/leagues/NBA_2019_per_game.html"

page <-
  url %>%
  read_html()

# Creates df that has columns: scheme (http), hostname(www.basketball-reference.com), and path(leagues/NBA_1997_per_game.htm)
url_df <- url %>%
  httr::parse_url() %>%
  flatten_df()
head(url_df,5)
      
      
      # Returns "1997_per_game"
url_path <-
  url_df$path %>% str_replace_all(".html|leagues/NBA_", "")
url_path

year_season_end <-
  url_path %>% 
  str_split('\\_') %>% 
  flatten_chr() %>% 
  .[[1]] %>% 
  as.character() %>% 
  readr::parse_number()

year_season_end

name_slug <-
  url_path %>%
  map_chr(function(x) {
    
    parts <- x %>% str_split('\\_') %>% flatten_chr()
    
    parts[2:length(parts)] %>% str_to_title() %>% str_c(collapse = '')
      })

name_slug

id_season <-
  list(year_season_end - 1, "-", year_season_end %>% str_sub(3, 4)) %>%
  purrr::reduce(paste0)
id_season

# Character Vector of Player Names
players <-
  page %>%
  html_nodes("th+ .left a") %>%
  html_text()
head(players, 5)

# Gets Player ID's Ex. "a/abdulma02.html"
player_id <-
  page %>%
  html_nodes("th+ .left a") %>%
  html_attr("href") %>%
  # "/players/a/abdulma02.html"
  str_replace_all("/players/", "")
head(player_id, 5)

player_ids <-
  player_id %>%
  map_chr(function(x) {
    x %>%
      # Get Player ID's and Remove .html. Ex. "a/abdulma02"
      str_replace_all(".html", "") %>%
      str_split("/") %>%
      flatten_chr() %>%
      .[[2]]
  })
head(player_ids, 5)

df_players <-
  tibble(slugPlayerBREF = player_ids, namePlayer = players) %>%
  distinct() %>%
  mutate(numberPlayer = 1:n()) %>%
  select(numberPlayer, everything())
head(df_players, 5)

df <-
  page %>%
  html_table() %>%
  .[[1]] %>%
  data.frame(stringsAsFactors = FALSE) %>%
  tbl_df() %>%
  dplyr::select(-dplyr::matches("Var"))
head(df, 5)

df <-
  df %>%
  mutate_at(
    df %>% dplyr::select(-one_of(c(
      "Tm", "Player", "Pos"
    ))) %>% names(),
    funs(. %>% as.numeric())
  ) %>%
  filter(!Rk %>% is.na()) %>%
  suppressWarnings()
head(df, 5)

      # df_players_unique <-
      #   df %>% group_by(Rk) %>% slice(1) %>%
      #   select(numberPlayer = Rk, namePlayer = Player) %>%
      #   ungroup()
      #
      # df <-
      #   df %>%
      #   dplyr::select(-dplyr::matches("Rk"))

df_names <-
  get_bref_name_df()
head(df_names, 5)

bref_names <-
  names(df)
head(bref_names, 5)

# Change Actual Names from df_bref
    actual_names <-
      seq_along(bref_names) %>%
      map_chr(function(x) {
        
# Extract Actual Name
        actual <-
          df_names %>%
          filter(nameBREF == bref_names[x]) %>%
          .$nameActual

        if (actual == 'MinutesPlayed') {
          if (!name_slug == 'pergame') {
            actual <-
              str_c('total', actual)
          } else {
            actual <-
              str_c('pergame', actual)
          }
          return(actual)
        }

        if (actual %>% substr(1, 1) %in% LETTERS) {
          actual <-
            str_c(name_slug, actual)
        }
        return(actual)
      })

head(actual_names, 5)

    df <-
      df %>%
      purrr::set_names(actual_names) %>%
      mutate(
        isHOFPlayer = namePlayer %>% str_detect('\\*'),
        namePlayer = namePlayer %>% str_replace_all('\\*', '')
      )
    
head(df, 5)

df <-
  df %>%
  left_join(df_players) %>%
  distinct() %>%
  suppressMessages() %>%
  mutate(
    slugSeason = id_season,
    yearSeason = year_season_end,
    urlData = url
  ) %>%
  dplyr::select(
    slugSeason, yearSeason,
    slugPlayerBREF, everything()
  )
head(df, 5)

df <-
  df %>%
  mutate_at(
    df %>% dplyr::select(dplyr::matches("pct")) %>% names(),
    funs(ifelse(. >= 1, . / 100, .))
  ) %>%
  mutate(typeData = name_slug) %>%
  dplyr::select(typeData, everything())

if (return_message) {
        list("parsed ", url) %>%
          purrr::reduce(paste0) %>%
          cat(fill = T)
      }

df <- 
  df %>%
  select(-one_of("numberPlayer"))
head(df, 5)

df <- 
  df %>%
  mutate_if(is.numeric, 
            list(function(x) {
          ifelse(is.na(x), 0, x)
        }))
head(df,5)

# Column Names getting pulled back into .get_data_bref
colnames(df)
```

